### ISSUE TITLE
Poor explanation of the validator custom rule, unique's syntax

### ISSUE THREAD

**Issue by lmj0011** [adonisjs/legacy-documentation#20]
http://adonisjs.com/docs/3.2/validator#_unique_tablename_fieldname
>AdonisJs supports all the validation rules by Indicative, but also adds a few who are specific to AdonisJs only

The syntax of the custom rule, `unique`, the only one adonis currently provides, could use better explaination

```js
'use strict'

class User extends Lucid {

  static rules (userId) {
    return {
      email: `unique:users,email,id,${userId}`
    }
  }

}
```

For example:

```js
email: unique:users,email,id,${userId}
```

There is nothing written to explain that `id` is needed if you're going to pass a `userId` to the rule.

I didn't infer that the first couple of times reading through the section.

I did something similiar to this:

```js
username: `unique:users,username,${userId}`
```

leaving out `id`, since it's already the primary key for the table.

Eventually I stuck `id` in there and it worked

**Comment by thetutlage** [comment]
Validations has nothing to do with the models, so it does not matter whether that is the primary key or not. 

The best can be done is to explain the purpose of all the params, so that they make more sense. 

Apart from that I don't think the example is too bad, since it works the way it has been described in the docs.
